stages:
  - build
  - test 

variables:
  DOCKER_REGISTRY: "YOUR-VALUE"
  IMAGE_NAME: "build-tools"
  TAG: 0.1.0
  HELM_REPO: "oci://YOUR-VALUE-HELM"
  HELM_LOGIN_URL: "https://YOUR-VALUE-HELM"

.default-before-script: &default-before-script 
  - 'echo "Runner info: $CI_RUNNER_DESCRIPTION"'
  - cat /etc/os-release
  - env | sort

build-image:
  stage: build
  image: quay.io/podman/stable:v5.4.2
  tags:
    - kubernetes
  before_script:
    - *default-before-script
  script:
    - $CI_PROJECT_DIR/run/build_and_push.sh

build-helm-chart:
  stage: build
  image: alpine/helm:3.12.0
  tags:
    - kubernetes
  before_script:    
    - *default-before-script
    - apk add --no-cache yq
    - helm version
    - yq --version
  script:
    - $CI_PROJECT_DIR/run/helm_package.sh
    - $CI_PROJECT_DIR/run/helm_publish.sh

test-image:
  stage: test
  image: ${DOCKER_REGISTRY}/${IMAGE_NAME}:${TAG}
  needs:
    - build-image
  tags:
    - kubernetes
  before_script:
    - *default-before-script
  script:
    - set -e  # Ensure job fails if any command fails
    - podman run --rm hello-world